spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://nitishsati:9IRkVBA29ASadFMa@cluster0.s3fu3.mongodb.net/productdb


server:
  servlet:
    context-path: /product

aws-secret:
  access-key: ${AWS_ACCESS_KEY_ID}
  access-key-id: ${AWS_SECRET_ACCESS_KEY}
  open-search-host: ${OPEN_SEARCH_HOST}
  open-search-user: ${OPEN_SEARCH_USER}
  open-search-password: ${OPEN_SEARCH_PASSWORD}

service-integration:
  inventory-service-url: localhost:8080/inventory
  order-service-url: localhost:8080/inventory

