spring:
  application:
    name: product-service
  elasticsearch:
    uris: ${ELASTIC_URI}
    username: ${ELASTIC_USER_NAME}
    password: ${ELASTIC_PASSWORD}
  data:
    mongodb:
      uri: mongodb+srv://nitishsati:9IRkVBA29ASadFMa@cluster0.s3fu3.mongodb.net/productdb


server:
  servlet:
    context-path: /product

aws-secret:
  access-key: ${AWS_SECRET_ACCESS_KEY}
  access-key-id: ${AWS_ACCESS_KEY_ID}

service-integration:
  inventory-service-url: localhost:8080/inventory
  order-service-url: localhost:8080/inventory

