name: Deploy Java App to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'adopt'

      - name: Build Project with Gradle
        run: gradle clean build  # Adjust if using Maven or another build tool

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Set SSH Directory Permissions
        run: chmod 700 ~/.ssh

      - name: Add EC2 Host to Known Hosts
        run: |
            ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts

            - name: Prepare SSH Key
              run: |
                echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
                chmod 600 ~/.ssh/ec2_key.pem

      - name: Deploy to EC2
        run: |
            scp -i ~/.ssh/ec2_key.pem build/libs/*.jar ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:~/productservice.jar
            ssh -i ~/.ssh/ec2_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
              if pgrep -f 'java -jar productservice.jar'; then
                pkill -f 'java -jar productservice.jar'
              fi
              nohup java -jar ~/productservice.jar > app.log 2>&1 &
            EOF